version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: awesome
      POSTGRES_USER: anabiev
      POSTGRES_PASSWORD: qwerty007
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
